### PR TITLE
Block Xposed Framework

### PR DESCRIPTION
**Pull request by jumoog**
Xposed can be used to stop AntiPiracySupport from working

### CODE REVIEW

**Comment by AlmightyMegadeth00** [comment]
xposed will not be added to this. Can you describe how it can circumvent the service? BTW v2 will be implemented internally in package manager so even if it does this won't be an issue

**Comment by jumoog** [comment]
hook into org.antipiracy.support.utils and replace every record of String[] PACKAGES with " "

**Comment by jumoog** [comment]
and detection by package name isn't very safe -> if i create lucky patcher and choose facebook package name as my package name and i'll will be save forever

**Comment by AlmightyMegadeth00** [comment]
Well thats why this is publicly maintained now so developers will continue to add the names regardless of how many times they are changed and if it's tracked from my github any update will reach all who support it.  Besides that's only the first version. There is a lot I have planned for this.

**Comment by AlmightyMegadeth00** [comment]
Jumoog if you want to collaborate you should pm me on hangouts

**Pull request closed without merging**
